//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ensurance.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode( "System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0" )]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable( EditorBrowsableState.Advanced )]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if ( ReferenceEquals( resourceMan, null ) )
                {
                    ResourceManager temp = new ResourceManager( "Ensurance.Properties.Resources", typeof (Resources).Assembly );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable( EditorBrowsableState.Advanced )]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot compare to null reference.
        /// </summary>
        internal static string CannotCompareToNullReference
        {
            get { return ResourceManager.GetString( "CannotCompareToNullReference", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot compare using a null reference.
        /// </summary>
        internal static string CannotCompareUsingNullReference
        {
            get { return ResourceManager.GetString( "CannotCompareUsingNullReference", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected and actual are both {0}.
        /// </summary>
        internal static string CollectionType_1
        {
            get { return ResourceManager.GetString( "CollectionType_1", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected is {0}, actual is {1}.
        /// </summary>
        internal static string CollectionType_2
        {
            get { return ResourceManager.GetString( "CollectionType_2", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler, log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  &lt;log4net&gt;
        ///    &lt;appender name=&quot;ColoredConsoleAppender&quot; type=&quot;log4net.Appender.ColoredConsoleAppender&quot;&gt;
        ///      &lt;mapping&gt;
        ///        &lt;level value=&quot;ERROR&quot; /&gt;
        ///        &lt;!--&lt;foreColor value=&quot;White&quot; /&gt;--&gt;
        ///        &lt;backColor value=&quot;Red, HighIntensity&quot; /&gt;
        ///      &lt;/mapping&gt;
        ///      &lt;mapping&gt;
        ///        &lt;level value=&quot;WARN&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLoggingConfiguration
        {
            get { return ResourceManager.GetString( "DefaultLoggingConfiguration", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to IEnsuranceHandler.Handle should not be used..
        /// </summary>
        internal static string IEnsuranceHandlerDoNotUse
        {
            get { return ResourceManager.GetString( "IEnsuranceHandlerDoNotUse", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stream lengths are both {0}. Streams differ at offset {1}..
        /// </summary>
        internal static string StreamsDiffer_1
        {
            get { return ResourceManager.GetString( "StreamsDiffer_1", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected Stream length {0} but was {1}..
        /// </summary>
        internal static string StreamsDiffer_2
        {
            get { return ResourceManager.GetString( "StreamsDiffer_2", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to String lengths are both {0}. Strings differ at index {1}..
        /// </summary>
        internal static string StringsDiffer_1
        {
            get { return ResourceManager.GetString( "StringsDiffer_1", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected string length {0} but was {1}. Strings differ at index {2}..
        /// </summary>
        internal static string StringsDiffer_2
        {
            get { return ResourceManager.GetString( "StringsDiffer_2", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The actual value must be a collection.
        /// </summary>
        internal static string ValueMustBeCollection
        {
            get { return ResourceManager.GetString( "ValueMustBeCollection", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Values differ at index {0}.
        /// </summary>
        internal static string ValuesDiffer_1
        {
            get { return ResourceManager.GetString( "ValuesDiffer_1", resourceCulture ); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Values differ at expected index {0}, actual index {1}.
        /// </summary>
        internal static string ValuesDiffer_2
        {
            get { return ResourceManager.GetString( "ValuesDiffer_2", resourceCulture ); }
        }
    }
}