//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensurance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ensurance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all items.
        /// </summary>
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all items unique.
        /// </summary>
        internal static string AllItemsUnique {
            get {
                return ResourceManager.GetString("AllItemsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare to null reference.
        /// </summary>
        internal static string CannotCompareToNullReference {
            get {
                return ResourceManager.GetString("CannotCompareToNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare using a null reference.
        /// </summary>
        internal static string CannotCompareUsingNullReference {
            get {
                return ResourceManager.GetString("CannotCompareUsingNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection containing.
        /// </summary>
        internal static string CollectionContaining {
            get {
                return ResourceManager.GetString("CollectionContaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected and actual are both {0}.
        /// </summary>
        internal static string CollectionType_1 {
            get {
                return ResourceManager.GetString("CollectionType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected is {0}, actual is {1}.
        /// </summary>
        internal static string CollectionType_2 {
            get {
                return ResourceManager.GetString("CollectionType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler, log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  &lt;log4net&gt;
        ///    &lt;appender name=&quot;ColoredConsoleAppender&quot; type=&quot;log4net.Appender.ColoredConsoleAppender&quot;&gt;
        ///      &lt;mapping&gt;
        ///        &lt;level value=&quot;ERROR&quot; /&gt;
        ///        &lt;!--&lt;foreColor value=&quot;White&quot; /&gt;--&gt;
        ///        &lt;backColor value=&quot;Red, HighIntensity&quot; /&gt;
        ///      &lt;/mapping&gt;
        ///      &lt;mapping&gt;
        ///        &lt;level value=&quot;WARN&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLoggingConfiguration {
            get {
                return ResourceManager.GetString("DefaultLoggingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a {1} property.
        /// </summary>
        internal static string DoesNotHaveProperty_2 {
            get {
                return ResourceManager.GetString("DoesNotHaveProperty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equivalent to.
        /// </summary>
        internal static string EquivalentTo {
            get {
                return ResourceManager.GetString("EquivalentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string Format_Char {
            get {
                return ResourceManager.GetString("Format_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} .
        /// </summary>
        internal static string Format_Connector {
            get {
                return ResourceManager.GetString("Format_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        internal static string Format_DateTime {
            get {
                return ResourceManager.GetString("Format_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string Format_Default {
            get {
                return ResourceManager.GetString("Format_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string Format_EmptyCollection {
            get {
                return ResourceManager.GetString("Format_EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;string.Empty&gt;.
        /// </summary>
        internal static string Format_EmptyString {
            get {
                return ResourceManager.GetString("Format_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}.
        /// </summary>
        internal static string Format_Modifier {
            get {
                return ResourceManager.GetString("Format_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string Format_Null {
            get {
                return ResourceManager.GetString("Format_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} .
        /// </summary>
        internal static string Format_Predicate {
            get {
                return ResourceManager.GetString("Format_Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string Format_String {
            get {
                return ResourceManager.GetString("Format_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Format_ValueType {
            get {
                return ResourceManager.GetString("Format_ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than or equal to.
        /// </summary>
        internal static string GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEnsuranceHandler.Handle should not be used..
        /// </summary>
        internal static string IEnsuranceHandlerDoNotUse {
            get {
                return ResourceManager.GetString("IEnsuranceHandlerDoNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignoring case.
        /// </summary>
        internal static string IgnoringCase {
            get {
                return ResourceManager.GetString("IgnoringCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instance of.
        /// </summary>
        internal static string InstanceOf {
            get {
                return ResourceManager.GetString("InstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than or equal to.
        /// </summary>
        internal static string LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no item.
        /// </summary>
        internal static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   But was:  .
        /// </summary>
        internal static string PrefixActual {
            get {
                return ResourceManager.GetString("PrefixActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Expected: .
        /// </summary>
        internal static string PrefixExpected {
            get {
                return ResourceManager.GetString("PrefixExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property \&quot;{0}\&quot;.
        /// </summary>
        internal static string PropertyName_1 {
            get {
                return ResourceManager.GetString("PropertyName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same as.
        /// </summary>
        internal static string SameAs {
            get {
                return ResourceManager.GetString("SameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some item.
        /// </summary>
        internal static string SomeItem {
            get {
                return ResourceManager.GetString("SomeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream lengths are both {0}. Streams differ at offset {1}..
        /// </summary>
        internal static string StreamsDiffer_1 {
            get {
                return ResourceManager.GetString("StreamsDiffer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Stream length {0} but was {1}..
        /// </summary>
        internal static string StreamsDiffer_2 {
            get {
                return ResourceManager.GetString("StreamsDiffer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String containing.
        /// </summary>
        internal static string StringContaining {
            get {
                return ResourceManager.GetString("StringContaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String ending with.
        /// </summary>
        internal static string StringEndingWith {
            get {
                return ResourceManager.GetString("StringEndingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String matching.
        /// </summary>
        internal static string StringMatching {
            get {
                return ResourceManager.GetString("StringMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String lengths are both {0}. Strings differ at index {1}..
        /// </summary>
        internal static string StringsDiffer_1 {
            get {
                return ResourceManager.GetString("StringsDiffer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string length {0} but was {1}. Strings differ at index {2}..
        /// </summary>
        internal static string StringsDiffer_2 {
            get {
                return ResourceManager.GetString("StringsDiffer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String starting with.
        /// </summary>
        internal static string StringStartingWith {
            get {
                return ResourceManager.GetString("StringStartingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subset of.
        /// </summary>
        internal static string SubsetOf {
            get {
                return ResourceManager.GetString("SubsetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type assignable from.
        /// </summary>
        internal static string TypeAssignableFrom {
            get {
                return ResourceManager.GetString("TypeAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNSET.
        /// </summary>
        internal static string UNSET {
            get {
                return ResourceManager.GetString("UNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual value must be a collection.
        /// </summary>
        internal static string ValueMustBeCollection {
            get {
                return ResourceManager.GetString("ValueMustBeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values differ at index {0}.
        /// </summary>
        internal static string ValuesDiffer_1 {
            get {
                return ResourceManager.GetString("ValuesDiffer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values differ at expected index {0}, actual index {1}.
        /// </summary>
        internal static string ValuesDiffer_2 {
            get {
                return ResourceManager.GetString("ValuesDiffer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with {0} elements.
        /// </summary>
        internal static string WithElements_1 {
            get {
                return ResourceManager.GetString("WithElements_1", resourceCulture);
            }
        }
    }
}
